let ADD_LIST = "ADD_LIST";
let GET_LISTS = "GET_LISTS";
let ADD_CARD = "ADD_CARD";
let MOVE_CARD = "MOVE_CARD";
let REMOVE_LIST = "REMOVE_LIST";

let ADD_BOARD = "ADD_BOARD";
let GET_ALL_BOARD = "GET_ALL_BOARD";
let REMOVE_BOARD = "REMOVE_BOARD";

export {
  //Lists
  ADD_LIST,
  GET_LISTS,
  ADD_CARD,
  MOVE_CARD,
  REMOVE_LIST,

  //Boards
  ADD_BOARD,
  GET_ALL_BOARD,
  REMOVE_BOARD
}